import os
import unittest
from Client import Client
from repositories.mocks.MockWikipediaRepository import MockWikipediaRepository


class ClientTestCase(unittest.TestCase):

    def setUp(self) -> None:
        self.client = Client()
        Client.wiki_repo = MockWikipediaRepository()

    def test_generate_mind_map_from_semi_structure_text(self):
        expected_result_output = {'nodes': [{'id': 1, 'text': "King Mongkut's University of Technology Thonburi"},
                                            {'id': 2, 'text': 'History'},
                                            {'id': 3, 'text': 'the Thonburi Technical College'},
                                            {'id': 4, 'text': '(TTC'}, {'id': 5, 'text': '4 February 1960'},
                                            {'id': 6, 'text': 'a new technology act'},
                                            {'id': 7, 'text': 'KMIT Thonburi campus'},
                                            {'id': 8, 'text': "King Mongkut's Institute of Technology"},
                                            {'id': 9, 'text': ' KMITT'}, {'id': 10, 'text': '460 acres'},
                                            {'id': 11, 'text': 'land'},
                                            {'id': 12, 'text': 'Governance and organisation'},
                                            {'id': 13, 'text': "the university's formal seal"},
                                            {'id': 14, 'text': 'the personal seal'}, {'id': 15, 'text': 'King Mongkut'},
                                            {'id': 16, 'text': 'a white tiered umbrella'},
                                            {'id': 17, 'text': 'kingship'}, {'id': 18, 'text': 'both sides'},
                                            {'id': 19, 'text': "the university's flower"},
                                            {'id': 20, 'text': 'Thammaruksa'}, {'id': 21, 'text': 'a flower'},
                                            {'id': 22, 'text': 'campus'}, {'id': 23, 'text': 'Faculties and Schools'},
                                            {'id': 24, 'text': 'School of Architecture and Design'},
                                            {'id': 25, 'text': " KMUTT's School of Architecture and Design"},
                                            {'id': 26, 'text': "the current bachelor's degree programs"},
                                            {'id': 27, 'text': 'architecture'},
                                            {'id': 28, 'text': 'interior architecture'},
                                            {'id': 29, 'text': 'industrial design'}, {'id': 30, 'text': 'the school'},
                                            {'id': 31, 'text': 'research'}, {'id': 32, 'text': 'development'},
                                            {'id': 33, 'text': 'applied technology'}, {'id': 34, 'text': 'art'},
                                            {'id': 35, 'text': 'design'}, {'id': 36, 'text': ' KMUTT'},
                                            {'id': 37, 'text': 'KMUTT'}, {'id': 38, 'text': 'Faculty'},
                                            {'id': 39, 'text': 'Faculty of Engineering'},
                                            {'id': 40, 'text': 'Engineering'}, {'id': 41, 'text': '(FoE'},
                                            {'id': 42, 'text': 'Faculty of Engineering'}, {'id': 43, 'text': 'Faculty'},
                                            {'id': 44, 'text': 'Faculty of Science'}, {'id': 45, 'text': 'Science'},
                                            {'id': 46, 'text': 'Faculty of Science'}, {'id': 47, 'text': '(FSci'},
                                            {'id': 48, 'text': 'Faculty of Science'}, {'id': 49, 'text': 'Faculty'},
                                            {'id': 50, 'text': 'Faculty of Industrial Education and Technology'},
                                            {'id': 51, 'text': 'Industrial Education'},
                                            {'id': 52, 'text': 'Technology'}, {'id': 53, 'text': '(FIET'},
                                            {'id': 54, 'text': 'Faculty of Industrial Education and Technology'},
                                            {'id': 55, 'text': 'School of Liberal Arts'},
                                            {'id': 56, 'text': 'School of Liberal Arts'}, {'id': 57, 'text': '(SoLA'},
                                            {'id': 58, 'text': 'School of Liberal Arts'},
                                            {'id': 59, 'text': 'School of Information Technology'},
                                            {'id': 60, 'text': 'School of Information Technology'},
                                            {'id': 61, 'text': '(SIT'},
                                            {'id': 62, 'text': 'School of Information Technology'},
                                            {'id': 63, 'text': 'Architecture'},
                                            {'id': 64, 'text': 'School of Architecture and Design'},
                                            {'id': 65, 'text': 'Design'},
                                            {'id': 66, 'text': 'School of Architecture and Design'},
                                            {'id': 67, 'text': 'School of Energy Environment and Materials (SEEM'},
                                            {'id': 68, 'text': 'School of Energy Environment and Materials'},
                                            {'id': 69, 'text': 'Bioresources'},
                                            {'id': 70, 'text': 'School of Bioresources and Technology'},
                                            {'id': 71, 'text': 'School of Bioresources and Technology'},
                                            {'id': 72, 'text': ' Join Graduate School'}, {'id': 73, 'text': 'Energy'},
                                            {'id': 74, 'text': 'Join Graduate School of Energy and Environment'},
                                            {'id': 75, 'text': 'Institute of Field Robotics'},
                                            {'id': 76, 'text': 'Institute of Field Robotics'},
                                            {'id': 77, 'text': '(FIBO'},
                                            {'id': 78, 'text': 'Institute of Field Robotics'},
                                            {'id': 79, 'text': 'Graduate School of Management and Innovation'},
                                            {'id': 80, 'text': 'Graduate School of Management and Innovation'},
                                            {'id': 81, 'text': 'Graduate School of Management and Innovation'},
                                            {'id': 82, 'text': '(GMI'},
                                            {'id': 83, 'text': 'Graduate School of Management and Innovation'},
                                            {'id': 84, 'text': 'College'},
                                            {'id': 85, 'text': 'College of Multidisciplinary Sciences'},
                                            {'id': 86, 'text': 'College of Multidisciplinary Sciences'},
                                            {'id': 87, 'text': 'Multidisciplinary Sciences'},
                                            {'id': 88, 'text': 'College of Multidisciplinary Sciences'},
                                            {'id': 89, 'text': 'College of Multidisciplinary Sciences'},
                                            {'id': 90, 'text': 'Student life'},
                                            {'id': 91, 'text': 'the sports complex'},
                                            {'id': 92, 'text': 'other facilities'}, {'id': 93, 'text': 'a gymnasium'},
                                            {'id': 94, 'text': 'a basketball court'}, {'id': 95, 'text': 'Library'},
                                            {'id': 96, 'text': "King Mongkut's University of Technology Thonburi"},
                                            {'id': 97, 'text': 'the management Central Office library'},
                                            {'id': 98, 'text': 'library'}, {'id': 99, 'text': ' KMUTT residence'},
                                            {'id': 100, 'text': 'student activities'},
                                            {'id': 101, 'text': 'sports services'},
                                            {'id': 102, 'text': 'sports equipment borrowing services'},
                                            {'id': 103, 'text': 'Campuses'}, {'id': 104, 'text': 'Bangmod main campus'},
                                            {'id': 105, 'text': 'the main campus'}, {'id': 106, 'text': '52 acres'},
                                            {'id': 107, 'text': '0.21 km2'},
                                            {'id': 108, 'text': 'the Faculty of Engineering'},
                                            {'id': 109, 'text': 'Faculty of Science'},
                                            {'id': 110, 'text': 'Faculty of Industrial Education and Technology'},
                                            {'id': 111, 'text': 'School of Energy, Environmental and Materials'},
                                            {'id': 112, 'text': 'the School of Information Technology'},
                                            {'id': 113, 'text': 'the School of Liberal Arts'},
                                            {'id': 114, 'text': 'Bang Khun Thian Campus'},
                                            {'id': 115, 'text': 'the Bang Khun Thian Campus'},
                                            {'id': 116, 'text': '80 acres'}, {'id': 117, 'text': '0.32 km2'},
                                            {'id': 118, 'text': '0.32 km2'}, {'id': 119, 'text': 'size'},
                                            {'id': 120, 'text': "Bangkok's Bang Khun Thian District"},
                                            {'id': 121, 'text': 'Ratchaburi Campus'},
                                            {'id': 122, 'text': 'the Ratchaburi campus'},
                                            {'id': 123, 'text': 'the main Bangmod campus'},
                                            {'id': 124, 'text': 'Bangkok'},
                                            {'id': 125, 'text': 'Main campus dormitories'},
                                            {'id': 126, 'text': 'the male dormitory'}, {'id': 127, 'text': 'a 23 m'},
                                            {'id': 128, 'text': '75 ft'}, {'id': 129, 'text': 'eleven-story building'},
                                            {'id': 130, 'text': 'the female dormitory'},
                                            {'id': 131, 'text': '(117 ft) ten-story building'},
                                            {'id': 132, 'text': 'Transportation'}, {'id': 133, 'text': ' KMUTT'},
                                            {'id': 134, 'text': 'a free bus service'},
                                            {'id': 135, 'text': 'the Bangmod campus'},
                                            {'id': 136, 'text': 'the Bang Khun Thian campus'},
                                            {'id': 137, 'text': 'the first trip'}, {'id': 138, 'text': '7:30 A.M.'},
                                            {'id': 139, 'text': 'the last trip'}, {'id': 140, 'text': 'KMUTT Library'},
                                            {'id': 141, 'text': 'KMUTT Library'},
                                            {'id': 142, 'text': 'Information Center'},
                                            {'id': 143, 'text': '5 May 1988'},
                                            {'id': 144, 'text': "King Mongkut's University of Technology Thonburi"},
                                            {'id': 145, 'text': 'an engineering and technology university'},
                                            {'id': 146, 'text': 'Thailand'},
                                            {'id': 147, 'text': 'nine national research universities'},
                                            {'id': 148, 'text': 'NRU'},
                                            {'id': 149, 'text': 'the third oldest engineering school'},
                                            {'id': 150, 'text': 'Thailand'},
                                            {'id': 151, 'text': 'seventh oldest university'}],
                                  'edges': [{'parentId': 1, 'childId': 2}, {'parentId': 2, 'childId': 3},
                                            {'parentId': 2, 'childId': 4}, {'parentId': 2, 'childId': 5},
                                            {'parentId': 2, 'childId': 6}, {'parentId': 2, 'childId': 7},
                                            {'parentId': 2, 'childId': 8}, {'parentId': 2, 'childId': 9},
                                            {'parentId': 2, 'childId': 10}, {'parentId': 2, 'childId': 11},
                                            {'parentId': 1, 'childId': 12}, {'parentId': 12, 'childId': 13},
                                            {'parentId': 12, 'childId': 14}, {'parentId': 12, 'childId': 15},
                                            {'parentId': 12, 'childId': 16}, {'parentId': 12, 'childId': 17},
                                            {'parentId': 12, 'childId': 18}, {'parentId': 12, 'childId': 19},
                                            {'parentId': 12, 'childId': 20}, {'parentId': 12, 'childId': 21},
                                            {'parentId': 12, 'childId': 22}, {'parentId': 1, 'childId': 23},
                                            {'parentId': 23, 'childId': 24}, {'parentId': 24, 'childId': 25},
                                            {'parentId': 24, 'childId': 26}, {'parentId': 24, 'childId': 27},
                                            {'parentId': 24, 'childId': 28}, {'parentId': 24, 'childId': 29},
                                            {'parentId': 24, 'childId': 30}, {'parentId': 24, 'childId': 31},
                                            {'parentId': 24, 'childId': 32}, {'parentId': 24, 'childId': 33},
                                            {'parentId': 24, 'childId': 34}, {'parentId': 24, 'childId': 35},
                                            {'parentId': 23, 'childId': 36}, {'parentId': 36, 'childId': 37},
                                            {'parentId': 23, 'childId': 38}, {'parentId': 38, 'childId': 39},
                                            {'parentId': 23, 'childId': 40}, {'parentId': 23, 'childId': 41},
                                            {'parentId': 41, 'childId': 42}, {'parentId': 23, 'childId': 43},
                                            {'parentId': 43, 'childId': 44}, {'parentId': 23, 'childId': 45},
                                            {'parentId': 45, 'childId': 46}, {'parentId': 23, 'childId': 47},
                                            {'parentId': 47, 'childId': 48}, {'parentId': 23, 'childId': 49},
                                            {'parentId': 49, 'childId': 50}, {'parentId': 23, 'childId': 51},
                                            {'parentId': 23, 'childId': 52}, {'parentId': 23, 'childId': 53},
                                            {'parentId': 53, 'childId': 54}, {'parentId': 23, 'childId': 55},
                                            {'parentId': 55, 'childId': 56}, {'parentId': 23, 'childId': 57},
                                            {'parentId': 57, 'childId': 58}, {'parentId': 23, 'childId': 59},
                                            {'parentId': 59, 'childId': 60}, {'parentId': 23, 'childId': 61},
                                            {'parentId': 61, 'childId': 62}, {'parentId': 23, 'childId': 63},
                                            {'parentId': 63, 'childId': 64}, {'parentId': 23, 'childId': 65},
                                            {'parentId': 65, 'childId': 66}, {'parentId': 23, 'childId': 67},
                                            {'parentId': 67, 'childId': 68}, {'parentId': 23, 'childId': 69},
                                            {'parentId': 69, 'childId': 70}, {'parentId': 69, 'childId': 71},
                                            {'parentId': 23, 'childId': 72}, {'parentId': 23, 'childId': 73},
                                            {'parentId': 73, 'childId': 74}, {'parentId': 23, 'childId': 75},
                                            {'parentId': 75, 'childId': 76}, {'parentId': 23, 'childId': 77},
                                            {'parentId': 77, 'childId': 78}, {'parentId': 23, 'childId': 79},
                                            {'parentId': 79, 'childId': 80}, {'parentId': 79, 'childId': 81},
                                            {'parentId': 23, 'childId': 82}, {'parentId': 82, 'childId': 83},
                                            {'parentId': 23, 'childId': 84}, {'parentId': 84, 'childId': 85},
                                            {'parentId': 84, 'childId': 86}, {'parentId': 23, 'childId': 87},
                                            {'parentId': 87, 'childId': 88}, {'parentId': 87, 'childId': 89},
                                            {'parentId': 1, 'childId': 90}, {'parentId': 90, 'childId': 91},
                                            {'parentId': 90, 'childId': 92}, {'parentId': 90, 'childId': 93},
                                            {'parentId': 90, 'childId': 94}, {'parentId': 90, 'childId': 95},
                                            {'parentId': 90, 'childId': 96}, {'parentId': 90, 'childId': 97},
                                            {'parentId': 90, 'childId': 98}, {'parentId': 90, 'childId': 99},
                                            {'parentId': 90, 'childId': 100}, {'parentId': 90, 'childId': 101},
                                            {'parentId': 90, 'childId': 102}, {'parentId': 1, 'childId': 103},
                                            {'parentId': 103, 'childId': 104}, {'parentId': 104, 'childId': 105},
                                            {'parentId': 104, 'childId': 106}, {'parentId': 104, 'childId': 107},
                                            {'parentId': 104, 'childId': 108}, {'parentId': 104, 'childId': 109},
                                            {'parentId': 104, 'childId': 110}, {'parentId': 104, 'childId': 111},
                                            {'parentId': 104, 'childId': 112}, {'parentId': 104, 'childId': 113},
                                            {'parentId': 103, 'childId': 114}, {'parentId': 114, 'childId': 115},
                                            {'parentId': 114, 'childId': 116}, {'parentId': 114, 'childId': 117},
                                            {'parentId': 117, 'childId': 118}, {'parentId': 114, 'childId': 119},
                                            {'parentId': 114, 'childId': 120}, {'parentId': 103, 'childId': 121},
                                            {'parentId': 121, 'childId': 122}, {'parentId': 121, 'childId': 123},
                                            {'parentId': 121, 'childId': 124}, {'parentId': 103, 'childId': 125},
                                            {'parentId': 125, 'childId': 126}, {'parentId': 125, 'childId': 127},
                                            {'parentId': 125, 'childId': 128}, {'parentId': 125, 'childId': 129},
                                            {'parentId': 125, 'childId': 130}, {'parentId': 125, 'childId': 131},
                                            {'parentId': 1, 'childId': 132}, {'parentId': 132, 'childId': 133},
                                            {'parentId': 132, 'childId': 134}, {'parentId': 132, 'childId': 135},
                                            {'parentId': 132, 'childId': 136}, {'parentId': 132, 'childId': 137},
                                            {'parentId': 132, 'childId': 138}, {'parentId': 132, 'childId': 139},
                                            {'parentId': 1, 'childId': 140}, {'parentId': 140, 'childId': 141},
                                            {'parentId': 140, 'childId': 142}, {'parentId': 140, 'childId': 143},
                                            {'parentId': 1, 'childId': 144}, {'parentId': 1, 'childId': 145},
                                            {'parentId': 1, 'childId': 146}, {'parentId': 1, 'childId': 147},
                                            {'parentId': 1, 'childId': 148}, {'parentId': 1, 'childId': 149},
                                            {'parentId': 149, 'childId': 150}, {'parentId': 1, 'childId': 151}]}

        actual_result = Client.generate_mind_map_from_semi_structure_text(
            """King_Mongkut's_University_of_Technology_Thonburi""")
        expected_string = str(expected_result_output)
        actual_string = str(actual_result)
        self.assertEqual(
            expected_string,
            actual_string,
            'structured: kmutt final output is not same as expected')

    def test_generate_mind_map_from_unstructured_text(self):
        expected_result_output = {'nodes': [
            {'id': 1, 'text': 'News - Apple helps Encircle expand its support for LGBTQ+ youth and their families'},
            {'id': 2, 'text': 'toelupe credits encircle'}, {'id': 3, 'text': 'Provo, Utah'},
            {'id': 4, 'text': 'his life'}, {'id': 5, 'text': 'Provo, Utah'}, {'id': 6, 'text': 'the nonprofit'},
            {'id': 7, 'text': 'Provo, Utah'}, {'id': 8, 'text': 'part'}, {'id': 9, 'text': 'Provo, Utah'},
            {'id': 10, 'text': 'toelupe'}, {'id': 11, 'text': 'Provo, Utah'}, {'id': 12, 'text': 'only a handful'},
            {'id': 13, 'text': 'gay students'}, {'id': 14, 'text': 'his high school'}, {'id': 15, 'text': 'rural Utah'},
            {'id': 16, 'text': 'Micah'}, {'id': 17, 'text': 'depression'}, {'id': 18, 'text': 'anxiety'},
            {'id': 19, 'text': 'social isolation'}, {'id': 20, 'text': 'the effect'}, {'id': 21, 'text': 'Micah'},
            {'id': 22, 'text': 'the house'}, {'id': 23, 'text': 'the nonprofit'}, {'id': 24, 'text': 'Utah'},
            {'id': 25, 'text': 'young LGBTQ+ people'}, {'id': 26, 'text': 'Utah'}, {'id': 27, 'text': 'their families'},
            {'id': 28, 'text': 'Utah'}, {'id': 29, 'text': 'support'}, {'id': 30, 'text': 'Utah'},
            {'id': 31, 'text': 'a sense'}, {'id': 32, 'text': 'Utah'}, {'id': 33, 'text': 'community resource houses'},
            {'id': 34, 'text': 'Utah'}, {'id': 35, 'text': 'a new campaign'}, {'id': 36, 'text': 'Utah'},
            {'id': 37, 'text': 'business'}, {'id': 38, 'text': 'Utah'}, {'id': 39, 'text': 'music'},
            {'id': 40, 'text': 'Utah'}, {'id': 41, 'text': 'technology'}, {'id': 42, 'text': 'Utah'},
            {'id': 43, 'text': 'the donations'}, {'id': 44, 'text': 'kickstart Encircle’s national expansion'},
            {'id': 45, 'text': 'addition'}, {'id': 46, 'text': 'a $1 million contribution'},
            {'id': 47, 'text': 'apple'}, {'id': 48, 'text': 'iPads'}, {'id': 49, 'text': 'other products'},
            {'id': 50, 'text': 'Encircle'}, {'id': 51, 'text': 'toelupe credits'}, {'id': 52, 'text': 'Provo, Utah'},
            {'id': 53, 'text': 'a little blue house'}, {'id': 54, 'text': 'Provo, Utah'}, {'id': 55, 'text': 'provo'},
            {'id': 56, 'text': 'Provo, Utah'}, {'id': 57, 'text': 'utah'}, {'id': 58, 'text': 'Provo, Utah'},
            {'id': 59, 'text': 'his life'}, {'id': 60, 'text': 'Provo, Utah'}, {'id': 61, 'text': 'the nonprofit'},
            {'id': 62, 'text': 'Provo, Utah'}, {'id': 63, 'text': 'a simple message'},
            {'id': 64, 'text': 'Provo, Utah'}, {'id': 65, 'text': 'No sides'}, {'id': 66, 'text': 'Provo, Utah'},
            {'id': 67, 'text': 'only a handful'}, {'id': 68, 'text': 'gay students'},
            {'id': 69, 'text': 'his high school'}, {'id': 70, 'text': 'rural Utah'}, {'id': 71, 'text': 'Micah'},
            {'id': 72, 'text': 'depression'}, {'id': 73, 'text': 'anxiety'}, {'id': 74, 'text': 'social isolation'},
            {'id': 75, 'text': 'the effect'}, {'id': 76, 'text': 'Micah'}, {'id': 77, 'text': 'the house'},
            {'id': 78, 'text': 'the nonprofit'}, {'id': 79, 'text': 'Utah'}, {'id': 80, 'text': 'young LGBTQ+ people'},
            {'id': 81, 'text': 'Utah'}, {'id': 82, 'text': 'their families'}, {'id': 83, 'text': 'Utah'},
            {'id': 84, 'text': 'support'}, {'id': 85, 'text': 'Utah'}, {'id': 86, 'text': 'a sense'},
            {'id': 87, 'text': 'Utah'}, {'id': 88, 'text': 'community resource houses'}, {'id': 89, 'text': 'Utah'},
            {'id': 90, 'text': 'a new campaign'}, {'id': 91, 'text': 'Utah'}, {'id': 92, 'text': 'business'},
            {'id': 93, 'text': 'Utah'}, {'id': 94, 'text': 'music'}, {'id': 95, 'text': 'Utah'},
            {'id': 96, 'text': 'technology'}, {'id': 97, 'text': 'Utah'}, {'id': 98, 'text': 'the donations'},
            {'id': 99, 'text': 'kickstart Encircle’s national expansion'}, {'id': 100, 'text': 'addition'},
            {'id': 101, 'text': 'a $1 million contribution'}, {'id': 102, 'text': 'apple'},
            {'id': 103, 'text': 'iPads'}, {'id': 104, 'text': 'other products'}, {'id': 105, 'text': 'Encircle'},
            {'id': 106, 'text': ' Encircle'}, {'id': 107, 'text': 'Encircle'}, {'id': 108, 'text': 'young people'},
            {'id': 109, 'text': 'Encircle'}, {'id': 110, 'text': 'their families'}, {'id': 111, 'text': 'Encircle'},
            {'id': 112, 'text': 'a number'}, {'id': 113, 'text': 'Encircle'}, {'id': 114, 'text': 'services'},
            {'id': 115, 'text': 'Encircle'}, {'id': 116, 'text': 'free and subsidized therapy sessions'},
            {'id': 117, 'text': 'Encircle'}, {'id': 118, 'text': 'Friendship Circle'}, {'id': 119, 'text': 'Encircle'},
            {'id': 120, 'text': 'the technology donations'}, {'id': 121, 'text': 'a meaningful difference'},
            {'id': 122, 'text': 'the nonprofit’s ability'}, {'id': 123, 'text': 'LGBTQ+ youth'},
            {'id': 124, 'text': 'the pandemic'}, {'id': 125, 'text': 'those services'}, {'id': 126, 'text': 'my life'},
            {'id': 127, 'text': 'my counselors'}, {'id': 128, 'text': 'my school'},
            {'id': 129, 'text': 'Micah Toelupe'}, {'id': 130, 'text': 'Micah Toelupe'},
            {'id': 131, 'text': ' Chrisann'}, {'id': 132, 'text': 'Utah'}, {'id': 133, 'text': 'Toelupe'},
            {'id': 134, 'text': 'Utah'}, {'id': 135, 'text': 'two LGBTQ-identified children'},
            {'id': 136, 'text': 'Utah'}, {'id': 137, 'text': 'their son'}, {'id': 138, 'text': 'Utah'},
            {'id': 139, 'text': 'Micah'}, {'id': 140, 'text': 'Utah'}, {'id': 141, 'text': 'her gender identity'},
            {'id': 142, 'text': 'Utah'}, {'id': 143, 'text': 'her parents'}, {'id': 144, 'text': 'Utah'},
            {'id': 145, 'text': 'Encircle'}, {'id': 146, 'text': 'Utah'}, {'id': 147, 'text': 'the Toe'},
            {'id': 148, 'text': 'Utah'}, {'id': 149, 'text': 'this whole network'}, {'id': 150, 'text': 'Encircle'},
            {'id': 151, 'text': 'people'}, {'id': 152, 'text': 'Encircle'}, {'id': 153, 'text': 'I'},
            {'id': 154, 'text': 'Encircle'}, {'id': 155, 'text': 'Chrisann'}, {'id': 156, 'text': 'Encircle'},
            {'id': 157, 'text': 'these other families'}, {'id': 158, 'text': 'Encircle'},
            {'id': 159, 'text': '10 LGBTQ+'}, {'id': 160, 'text': 'Encircle'}, {'id': 161, 'text': 'people'},
            {'id': 162, 'text': 'Encircle'}, {'id': 163, 'text': 'suicide'}, {'id': 164, 'text': 'Encircle'},
            {'id': 165, 'text': 'the past 12 months'}, {'id': 166, 'text': 'Encircle'}, {'id': 167, 'text': 'LGBTQ+'},
            {'id': 168, 'text': 'Encircle'}, {'id': 169, 'text': 'a part'}, {'id': 170, 'text': 'the communities'},
            {'id': 171, 'text': 'the nonprofit prides'}, {'id': 172, 'text': 'more than 10,000 guests'},
            {'id': 173, 'text': 'each Encircle home'}, {'id': 174, 'text': 'counseling services'},
            {'id': 175, 'text': 'music nights'}, {'id': 176, 'text': 'community service projects'},
            {'id': 177, 'text': 'other bonding activities'}, {'id': 178, 'text': 'the Toelupes'},
            {'id': 179, 'text': 'a house'}, {'id': 180, 'text': 'Provo'}, {'id': 181, 'text': 'Provo'},
            {'id': 182, 'text': 'just 20 minutes'}, {'id': 183, 'text': 'their home'},
            {'id': 184, 'text': 'some local resources'}, {'id': 185, 'text': ' Khristian Toelupes'},
            {'id': 186, 'text': 'her mission'}, {'id': 187, 'text': 'the Philippines'},
            {'id': 188, 'text': 'a support system'}, {'id': 189, 'text': 'anything'}, {'id': 190, 'text': 'I'},
            {'id': 191, 'text': 'Encircle'}, {'id': 192, 'text': 'the nonprofit'},
            {'id': 193, 'text': 'a deeper understanding'}, {'id': 194, 'text': 'appreciation'},
            {'id': 195, 'text': 'a diversity'}, {'id': 196, 'text': 'experiences'}, {'id': 197, 'text': 'identities'},
            {'id': 198, 'text': 'students'}, {'id': 199, 'text': 'hours'}, {'id': 200, 'text': 'a time'},
            {'id': 201, 'text': 'the Friendship Circles'}, {'id': 202, 'text': 'two people'},
            {'id': 203, 'text': 'the first group'}, {'id': 204, 'text': '20 kids'}, {'id': 205, 'text': 'the room'},
            {'id': 206, 'text': 'my life'}, {'id': 207, 'text': 'then my counselors'},
            {'id': 208, 'text': 'Savannah Harman'}, {'id': 209, 'text': 'Salt Lake City house'},
            {'id': 210, 'text': 'Encircle’s Salt Lake City house'}, {'id': 211, 'text': 'Salt Lake City house'},
            {'id': 212, 'text': 'Friendship Circles'}, {'id': 213, 'text': 'Salt Lake City house'},
            {'id': 214, 'text': 'other community-building activities'}, {'id': 215, 'text': 'Salt Lake City house'},
            {'id': 216, 'text': 'supportive friends'}, {'id': 217, 'text': 'Salt Lake City house'},
            {'id': 218, 'text': 'all walks'}, {'id': 219, 'text': 'LGBTQ+ youth'},
            {'id': 220, 'text': 'Salt Lake City house'}, {'id': 221, 'text': 'life'},
            {'id': 222, 'text': 'Salt Lake City house'}, {'id': 223, 'text': ' Encircle'}, {'id': 224, 'text': 'space'},
            {'id': 225, 'text': 'your family'}, {'id': 226, 'text': " micah's mom"},
            {'id': 227, 'text': 'an enthusiastic first customer'}, {'id': 228, 'text': 'the piece'},
            {'id': 229, 'text': 'Micah'}, {'id': 230, 'text': 'the Toelupes’ living room'}, {'id': 231, 'text': 'I'},
            {'id': 232, 'text': 'Chrisann'}, {'id': 233, 'text': 'Encircle'}, {'id': 234, 'text': '"it'},
            {'id': 235, 'text': 'Encircle'}, {'id': 236, 'text': 'Micah'}, {'id': 237, 'text': 'Encircle'},
            {'id': 238, 'text': ' free and subsidized therapy sessions'}, {'id': 239, 'text': 'Friendship Circles'},
            {'id': 240, 'text': 'safe spaces'}, {'id': 241, 'text': 'foster community'},
            {'id': 242, 'text': 'an open door policy'}, {'id': 243, 'text': 'everyone'},
            {'id': 244, 'text': 'their doors'}, {'id': 245, 'text': 'the technology donations'},
            {'id': 246, 'text': 'a meaningful difference'}, {'id': 247, 'text': 'the nonprofit’s ability'},
            {'id': 248, 'text': 'LGBTQ+ youth'}, {'id': 249, 'text': 'the pandemic'},
            {'id': 250, 'text': 'those services'}, {'id': 251, 'text': 'my life'}, {'id': 252, 'text': 'my counselors'},
            {'id': 253, 'text': 'my school'}, {'id': 254, 'text': 'Micah Toelupe'},
            {'id': 255, 'text': 'Micah Toelupe'}, {'id': 256, 'text': ' Chrisann'}, {'id': 257, 'text': 'Utah'},
            {'id': 258, 'text': 'Toelupe'}, {'id': 259, 'text': 'Utah'},
            {'id': 260, 'text': 'two LGBTQ-identified children'}, {'id': 261, 'text': 'Utah'},
            {'id': 262, 'text': 'their son'}, {'id': 263, 'text': 'Utah'}, {'id': 264, 'text': 'Micah'},
            {'id': 265, 'text': 'Utah'}, {'id': 266, 'text': 'her gender identity'}, {'id': 267, 'text': 'Utah'},
            {'id': 268, 'text': 'her parents'}, {'id': 269, 'text': 'Utah'}, {'id': 270, 'text': 'Encircle'},
            {'id': 271, 'text': 'Utah'}, {'id': 272, 'text': 'the Toe'}, {'id': 273, 'text': 'Utah'},
            {'id': 274, 'text': 'this whole network'}, {'id': 275, 'text': 'Encircle'}, {'id': 276, 'text': 'people'},
            {'id': 277, 'text': 'Encircle'}, {'id': 278, 'text': 'I'}, {'id': 279, 'text': 'Encircle'},
            {'id': 280, 'text': 'Chrisann'}, {'id': 281, 'text': 'Encircle'},
            {'id': 282, 'text': 'these other families'}, {'id': 283, 'text': 'Encircle'},
            {'id': 284, 'text': '10 LGBTQ+'}, {'id': 285, 'text': 'Encircle'}, {'id': 286, 'text': 'people'},
            {'id': 287, 'text': 'Encircle'}, {'id': 288, 'text': 'suicide'}, {'id': 289, 'text': 'Encircle'},
            {'id': 290, 'text': 'the past 12 months'}, {'id': 291, 'text': 'Encircle'}, {'id': 292, 'text': 'LGBTQ+'},
            {'id': 293, 'text': 'Encircle'}, {'id': 294, 'text': 'a part'}, {'id': 295, 'text': 'the communities'},
            {'id': 296, 'text': 'the nonprofit prides'}, {'id': 297, 'text': 'more than 10,000 guests'},
            {'id': 298, 'text': 'each Encircle home'}, {'id': 299, 'text': 'counseling services'},
            {'id': 300, 'text': 'music nights'}, {'id': 301, 'text': 'community service projects'},
            {'id': 302, 'text': 'other bonding activities'}, {'id': 303, 'text': 'the Toelupes'},
            {'id': 304, 'text': 'a house'}, {'id': 305, 'text': 'Provo'}, {'id': 306, 'text': 'Provo'},
            {'id': 307, 'text': 'just 20 minutes'}, {'id': 308, 'text': 'their home'},
            {'id': 309, 'text': 'some local resources'}, {'id': 310, 'text': ' Khristian Toelupes'},
            {'id': 311, 'text': 'her mission'}, {'id': 312, 'text': 'the Philippines'},
            {'id': 313, 'text': 'a support system'}, {'id': 314, 'text': 'anything'}, {'id': 315, 'text': 'I'},
            {'id': 316, 'text': 'Encircle'}, {'id': 317, 'text': 'the nonprofit'},
            {'id': 318, 'text': 'a deeper understanding'}, {'id': 319, 'text': 'appreciation'},
            {'id': 320, 'text': 'a diversity'}, {'id': 321, 'text': 'experiences'}, {'id': 322, 'text': 'identities'},
            {'id': 323, 'text': 'students'}, {'id': 324, 'text': 'hours'}, {'id': 325, 'text': 'a time'},
            {'id': 326, 'text': 'the Friendship Circles'}, {'id': 327, 'text': 'two people'},
            {'id': 328, 'text': 'the first group'}, {'id': 329, 'text': '20 kids'}, {'id': 330, 'text': 'the room'},
            {'id': 331, 'text': 'my life'}, {'id': 332, 'text': 'then my counselors'},
            {'id': 333, 'text': 'Savannah Harman'}, {'id': 334, 'text': 'Salt Lake City house'},
            {'id': 335, 'text': 'Encircle’s Salt Lake City house'}, {'id': 336, 'text': 'Salt Lake City house'},
            {'id': 337, 'text': 'Friendship Circles'}, {'id': 338, 'text': 'Salt Lake City house'},
            {'id': 339, 'text': 'other community-building activities'}, {'id': 340, 'text': 'Salt Lake City house'},
            {'id': 341, 'text': 'supportive friends'}, {'id': 342, 'text': 'Salt Lake City house'},
            {'id': 343, 'text': 'all walks'}, {'id': 344, 'text': 'LGBTQ+ youth'},
            {'id': 345, 'text': 'Salt Lake City house'}, {'id': 346, 'text': 'life'},
            {'id': 347, 'text': 'Salt Lake City house'}, {'id': 348, 'text': ' Encircle'}, {'id': 349, 'text': 'space'},
            {'id': 350, 'text': 'your family'}, {'id': 351, 'text': " micah's mom"},
            {'id': 352, 'text': 'an enthusiastic first customer'}, {'id': 353, 'text': 'the piece'},
            {'id': 354, 'text': 'Micah'}, {'id': 355, 'text': 'the Toelupes’ living room'}, {'id': 356, 'text': 'I'},
            {'id': 357, 'text': 'Chrisann'}, {'id': 358, 'text': 'Encircle'}, {'id': 359, 'text': '"it'},
            {'id': 360, 'text': 'Encircle'}, {'id': 361, 'text': 'Micah'}, {'id': 362, 'text': 'Encircle'},
            {'id': 363, 'text': 'Encircle'}], 'edges': [{'parentId': 1, 'childId': 2}, {'parentId': 2, 'childId': 3},
                                                        {'parentId': 1, 'childId': 4}, {'parentId': 4, 'childId': 5},
                                                        {'parentId': 1, 'childId': 6}, {'parentId': 6, 'childId': 7},
                                                        {'parentId': 1, 'childId': 8}, {'parentId': 8, 'childId': 9},
                                                        {'parentId': 1, 'childId': 10}, {'parentId': 10, 'childId': 11},
                                                        {'parentId': 1, 'childId': 12}, {'parentId': 1, 'childId': 13},
                                                        {'parentId': 1, 'childId': 14}, {'parentId': 1, 'childId': 15},
                                                        {'parentId': 1, 'childId': 16}, {'parentId': 1, 'childId': 17},
                                                        {'parentId': 1, 'childId': 18}, {'parentId': 1, 'childId': 19},
                                                        {'parentId': 1, 'childId': 20}, {'parentId': 1, 'childId': 21},
                                                        {'parentId': 1, 'childId': 22}, {'parentId': 1, 'childId': 23},
                                                        {'parentId': 23, 'childId': 24}, {'parentId': 1, 'childId': 25},
                                                        {'parentId': 25, 'childId': 26}, {'parentId': 1, 'childId': 27},
                                                        {'parentId': 27, 'childId': 28}, {'parentId': 1, 'childId': 29},
                                                        {'parentId': 29, 'childId': 30}, {'parentId': 1, 'childId': 31},
                                                        {'parentId': 31, 'childId': 32}, {'parentId': 1, 'childId': 33},
                                                        {'parentId': 33, 'childId': 34}, {'parentId': 1, 'childId': 35},
                                                        {'parentId': 35, 'childId': 36}, {'parentId': 1, 'childId': 37},
                                                        {'parentId': 37, 'childId': 38}, {'parentId': 1, 'childId': 39},
                                                        {'parentId': 39, 'childId': 40}, {'parentId': 1, 'childId': 41},
                                                        {'parentId': 41, 'childId': 42}, {'parentId': 1, 'childId': 43},
                                                        {'parentId': 1, 'childId': 44}, {'parentId': 1, 'childId': 45},
                                                        {'parentId': 1, 'childId': 46}, {'parentId': 1, 'childId': 47},
                                                        {'parentId': 1, 'childId': 48}, {'parentId': 1, 'childId': 49},
                                                        {'parentId': 1, 'childId': 50}, {'parentId': 1, 'childId': 51},
                                                        {'parentId': 51, 'childId': 52}, {'parentId': 1, 'childId': 53},
                                                        {'parentId': 53, 'childId': 54}, {'parentId': 1, 'childId': 55},
                                                        {'parentId': 55, 'childId': 56}, {'parentId': 1, 'childId': 57},
                                                        {'parentId': 57, 'childId': 58}, {'parentId': 1, 'childId': 59},
                                                        {'parentId': 59, 'childId': 60}, {'parentId': 1, 'childId': 61},
                                                        {'parentId': 61, 'childId': 62}, {'parentId': 1, 'childId': 63},
                                                        {'parentId': 63, 'childId': 64}, {'parentId': 1, 'childId': 65},
                                                        {'parentId': 65, 'childId': 66}, {'parentId': 1, 'childId': 67},
                                                        {'parentId': 1, 'childId': 68}, {'parentId': 1, 'childId': 69},
                                                        {'parentId': 1, 'childId': 70}, {'parentId': 1, 'childId': 71},
                                                        {'parentId': 1, 'childId': 72}, {'parentId': 1, 'childId': 73},
                                                        {'parentId': 1, 'childId': 74}, {'parentId': 1, 'childId': 75},
                                                        {'parentId': 1, 'childId': 76}, {'parentId': 1, 'childId': 77},
                                                        {'parentId': 1, 'childId': 78}, {'parentId': 78, 'childId': 79},
                                                        {'parentId': 1, 'childId': 80}, {'parentId': 80, 'childId': 81},
                                                        {'parentId': 1, 'childId': 82}, {'parentId': 82, 'childId': 83},
                                                        {'parentId': 1, 'childId': 84}, {'parentId': 84, 'childId': 85},
                                                        {'parentId': 1, 'childId': 86}, {'parentId': 86, 'childId': 87},
                                                        {'parentId': 1, 'childId': 88}, {'parentId': 88, 'childId': 89},
                                                        {'parentId': 1, 'childId': 90}, {'parentId': 90, 'childId': 91},
                                                        {'parentId': 1, 'childId': 92}, {'parentId': 92, 'childId': 93},
                                                        {'parentId': 1, 'childId': 94}, {'parentId': 94, 'childId': 95},
                                                        {'parentId': 1, 'childId': 96}, {'parentId': 96, 'childId': 97},
                                                        {'parentId': 1, 'childId': 98}, {'parentId': 1, 'childId': 99},
                                                        {'parentId': 1, 'childId': 100},
                                                        {'parentId': 1, 'childId': 101},
                                                        {'parentId': 1, 'childId': 102},
                                                        {'parentId': 1, 'childId': 103},
                                                        {'parentId': 1, 'childId': 104},
                                                        {'parentId': 1, 'childId': 105},
                                                        {'parentId': 1, 'childId': 106},
                                                        {'parentId': 106, 'childId': 107},
                                                        {'parentId': 1, 'childId': 108},
                                                        {'parentId': 108, 'childId': 109},
                                                        {'parentId': 1, 'childId': 110},
                                                        {'parentId': 110, 'childId': 111},
                                                        {'parentId': 1, 'childId': 112},
                                                        {'parentId': 112, 'childId': 113},
                                                        {'parentId': 1, 'childId': 114},
                                                        {'parentId': 114, 'childId': 115},
                                                        {'parentId': 1, 'childId': 116},
                                                        {'parentId': 116, 'childId': 117},
                                                        {'parentId': 1, 'childId': 118},
                                                        {'parentId': 118, 'childId': 119},
                                                        {'parentId': 1, 'childId': 120},
                                                        {'parentId': 1, 'childId': 121},
                                                        {'parentId': 1, 'childId': 122},
                                                        {'parentId': 1, 'childId': 123},
                                                        {'parentId': 1, 'childId': 124},
                                                        {'parentId': 1, 'childId': 125},
                                                        {'parentId': 1, 'childId': 126},
                                                        {'parentId': 1, 'childId': 127},
                                                        {'parentId': 1, 'childId': 128},
                                                        {'parentId': 1, 'childId': 129},
                                                        {'parentId': 129, 'childId': 130},
                                                        {'parentId': 1, 'childId': 131},
                                                        {'parentId': 131, 'childId': 132},
                                                        {'parentId': 1, 'childId': 133},
                                                        {'parentId': 133, 'childId': 134},
                                                        {'parentId': 1, 'childId': 135},
                                                        {'parentId': 135, 'childId': 136},
                                                        {'parentId': 1, 'childId': 137},
                                                        {'parentId': 137, 'childId': 138},
                                                        {'parentId': 1, 'childId': 139},
                                                        {'parentId': 139, 'childId': 140},
                                                        {'parentId': 1, 'childId': 141},
                                                        {'parentId': 141, 'childId': 142},
                                                        {'parentId': 1, 'childId': 143},
                                                        {'parentId': 143, 'childId': 144},
                                                        {'parentId': 1, 'childId': 145},
                                                        {'parentId': 145, 'childId': 146},
                                                        {'parentId': 1, 'childId': 147},
                                                        {'parentId': 147, 'childId': 148},
                                                        {'parentId': 1, 'childId': 149},
                                                        {'parentId': 149, 'childId': 150},
                                                        {'parentId': 1, 'childId': 151},
                                                        {'parentId': 151, 'childId': 152},
                                                        {'parentId': 1, 'childId': 153},
                                                        {'parentId': 153, 'childId': 154},
                                                        {'parentId': 1, 'childId': 155},
                                                        {'parentId': 155, 'childId': 156},
                                                        {'parentId': 1, 'childId': 157},
                                                        {'parentId': 157, 'childId': 158},
                                                        {'parentId': 1, 'childId': 159},
                                                        {'parentId': 159, 'childId': 160},
                                                        {'parentId': 1, 'childId': 161},
                                                        {'parentId': 161, 'childId': 162},
                                                        {'parentId': 1, 'childId': 163},
                                                        {'parentId': 163, 'childId': 164},
                                                        {'parentId': 1, 'childId': 165},
                                                        {'parentId': 165, 'childId': 166},
                                                        {'parentId': 1, 'childId': 167},
                                                        {'parentId': 167, 'childId': 168},
                                                        {'parentId': 1, 'childId': 169},
                                                        {'parentId': 1, 'childId': 170},
                                                        {'parentId': 1, 'childId': 171},
                                                        {'parentId': 1, 'childId': 172},
                                                        {'parentId': 1, 'childId': 173},
                                                        {'parentId': 1, 'childId': 174},
                                                        {'parentId': 1, 'childId': 175},
                                                        {'parentId': 1, 'childId': 176},
                                                        {'parentId': 1, 'childId': 177},
                                                        {'parentId': 1, 'childId': 178},
                                                        {'parentId': 1, 'childId': 179},
                                                        {'parentId': 179, 'childId': 180},
                                                        {'parentId': 1, 'childId': 181},
                                                        {'parentId': 1, 'childId': 182},
                                                        {'parentId': 1, 'childId': 183},
                                                        {'parentId': 1, 'childId': 184},
                                                        {'parentId': 1, 'childId': 185},
                                                        {'parentId': 1, 'childId': 186},
                                                        {'parentId': 1, 'childId': 187},
                                                        {'parentId': 1, 'childId': 188},
                                                        {'parentId': 1, 'childId': 189},
                                                        {'parentId': 1, 'childId': 190},
                                                        {'parentId': 1, 'childId': 191},
                                                        {'parentId': 1, 'childId': 192},
                                                        {'parentId': 1, 'childId': 193},
                                                        {'parentId': 1, 'childId': 194},
                                                        {'parentId': 1, 'childId': 195},
                                                        {'parentId': 1, 'childId': 196},
                                                        {'parentId': 1, 'childId': 197},
                                                        {'parentId': 1, 'childId': 198},
                                                        {'parentId': 1, 'childId': 199},
                                                        {'parentId': 1, 'childId': 200},
                                                        {'parentId': 1, 'childId': 201},
                                                        {'parentId': 1, 'childId': 202},
                                                        {'parentId': 1, 'childId': 203},
                                                        {'parentId': 1, 'childId': 204},
                                                        {'parentId': 1, 'childId': 205},
                                                        {'parentId': 1, 'childId': 206},
                                                        {'parentId': 1, 'childId': 207},
                                                        {'parentId': 1, 'childId': 208},
                                                        {'parentId': 208, 'childId': 209},
                                                        {'parentId': 1, 'childId': 210},
                                                        {'parentId': 210, 'childId': 211},
                                                        {'parentId': 1, 'childId': 212},
                                                        {'parentId': 212, 'childId': 213},
                                                        {'parentId': 1, 'childId': 214},
                                                        {'parentId': 214, 'childId': 215},
                                                        {'parentId': 1, 'childId': 216},
                                                        {'parentId': 216, 'childId': 217},
                                                        {'parentId': 1, 'childId': 218},
                                                        {'parentId': 218, 'childId': 219},
                                                        {'parentId': 218, 'childId': 220},
                                                        {'parentId': 1, 'childId': 221},
                                                        {'parentId': 221, 'childId': 222},
                                                        {'parentId': 1, 'childId': 223},
                                                        {'parentId': 1, 'childId': 224},
                                                        {'parentId': 1, 'childId': 225},
                                                        {'parentId': 1, 'childId': 226},
                                                        {'parentId': 1, 'childId': 227},
                                                        {'parentId': 1, 'childId': 228},
                                                        {'parentId': 1, 'childId': 229},
                                                        {'parentId': 1, 'childId': 230},
                                                        {'parentId': 1, 'childId': 231},
                                                        {'parentId': 1, 'childId': 232},
                                                        {'parentId': 232, 'childId': 233},
                                                        {'parentId': 1, 'childId': 234},
                                                        {'parentId': 234, 'childId': 235},
                                                        {'parentId': 1, 'childId': 236},
                                                        {'parentId': 236, 'childId': 237},
                                                        {'parentId': 1, 'childId': 238},
                                                        {'parentId': 1, 'childId': 239},
                                                        {'parentId': 1, 'childId': 240},
                                                        {'parentId': 1, 'childId': 241},
                                                        {'parentId': 1, 'childId': 242},
                                                        {'parentId': 1, 'childId': 243},
                                                        {'parentId': 1, 'childId': 244},
                                                        {'parentId': 1, 'childId': 245},
                                                        {'parentId': 1, 'childId': 246},
                                                        {'parentId': 1, 'childId': 247},
                                                        {'parentId': 1, 'childId': 248},
                                                        {'parentId': 1, 'childId': 249},
                                                        {'parentId': 1, 'childId': 250},
                                                        {'parentId': 1, 'childId': 251},
                                                        {'parentId': 1, 'childId': 252},
                                                        {'parentId': 1, 'childId': 253},
                                                        {'parentId': 1, 'childId': 254},
                                                        {'parentId': 254, 'childId': 255},
                                                        {'parentId': 1, 'childId': 256},
                                                        {'parentId': 256, 'childId': 257},
                                                        {'parentId': 1, 'childId': 258},
                                                        {'parentId': 258, 'childId': 259},
                                                        {'parentId': 1, 'childId': 260},
                                                        {'parentId': 260, 'childId': 261},
                                                        {'parentId': 1, 'childId': 262},
                                                        {'parentId': 262, 'childId': 263},
                                                        {'parentId': 1, 'childId': 264},
                                                        {'parentId': 264, 'childId': 265},
                                                        {'parentId': 1, 'childId': 266},
                                                        {'parentId': 266, 'childId': 267},
                                                        {'parentId': 1, 'childId': 268},
                                                        {'parentId': 268, 'childId': 269},
                                                        {'parentId': 1, 'childId': 270},
                                                        {'parentId': 270, 'childId': 271},
                                                        {'parentId': 1, 'childId': 272},
                                                        {'parentId': 272, 'childId': 273},
                                                        {'parentId': 1, 'childId': 274},
                                                        {'parentId': 274, 'childId': 275},
                                                        {'parentId': 1, 'childId': 276},
                                                        {'parentId': 276, 'childId': 277},
                                                        {'parentId': 1, 'childId': 278},
                                                        {'parentId': 278, 'childId': 279},
                                                        {'parentId': 1, 'childId': 280},
                                                        {'parentId': 280, 'childId': 281},
                                                        {'parentId': 1, 'childId': 282},
                                                        {'parentId': 282, 'childId': 283},
                                                        {'parentId': 1, 'childId': 284},
                                                        {'parentId': 284, 'childId': 285},
                                                        {'parentId': 1, 'childId': 286},
                                                        {'parentId': 286, 'childId': 287},
                                                        {'parentId': 1, 'childId': 288},
                                                        {'parentId': 288, 'childId': 289},
                                                        {'parentId': 1, 'childId': 290},
                                                        {'parentId': 290, 'childId': 291},
                                                        {'parentId': 1, 'childId': 292},
                                                        {'parentId': 292, 'childId': 293},
                                                        {'parentId': 1, 'childId': 294},
                                                        {'parentId': 1, 'childId': 295},
                                                        {'parentId': 1, 'childId': 296},
                                                        {'parentId': 1, 'childId': 297},
                                                        {'parentId': 1, 'childId': 298},
                                                        {'parentId': 1, 'childId': 299},
                                                        {'parentId': 1, 'childId': 300},
                                                        {'parentId': 1, 'childId': 301},
                                                        {'parentId': 1, 'childId': 302},
                                                        {'parentId': 1, 'childId': 303},
                                                        {'parentId': 1, 'childId': 304},
                                                        {'parentId': 304, 'childId': 305},
                                                        {'parentId': 1, 'childId': 306},
                                                        {'parentId': 1, 'childId': 307},
                                                        {'parentId': 1, 'childId': 308},
                                                        {'parentId': 1, 'childId': 309},
                                                        {'parentId': 1, 'childId': 310},
                                                        {'parentId': 1, 'childId': 311},
                                                        {'parentId': 1, 'childId': 312},
                                                        {'parentId': 1, 'childId': 313},
                                                        {'parentId': 1, 'childId': 314},
                                                        {'parentId': 1, 'childId': 315},
                                                        {'parentId': 1, 'childId': 316},
                                                        {'parentId': 1, 'childId': 317},
                                                        {'parentId': 1, 'childId': 318},
                                                        {'parentId': 1, 'childId': 319},
                                                        {'parentId': 1, 'childId': 320},
                                                        {'parentId': 1, 'childId': 321},
                                                        {'parentId': 1, 'childId': 322},
                                                        {'parentId': 1, 'childId': 323},
                                                        {'parentId': 1, 'childId': 324},
                                                        {'parentId': 1, 'childId': 325},
                                                        {'parentId': 1, 'childId': 326},
                                                        {'parentId': 1, 'childId': 327},
                                                        {'parentId': 1, 'childId': 328},
                                                        {'parentId': 1, 'childId': 329},
                                                        {'parentId': 1, 'childId': 330},
                                                        {'parentId': 1, 'childId': 331},
                                                        {'parentId': 1, 'childId': 332},
                                                        {'parentId': 1, 'childId': 333},
                                                        {'parentId': 333, 'childId': 334},
                                                        {'parentId': 1, 'childId': 335},
                                                        {'parentId': 335, 'childId': 336},
                                                        {'parentId': 1, 'childId': 337},
                                                        {'parentId': 337, 'childId': 338},
                                                        {'parentId': 1, 'childId': 339},
                                                        {'parentId': 339, 'childId': 340},
                                                        {'parentId': 1, 'childId': 341},
                                                        {'parentId': 341, 'childId': 342},
                                                        {'parentId': 1, 'childId': 343},
                                                        {'parentId': 343, 'childId': 344},
                                                        {'parentId': 343, 'childId': 345},
                                                        {'parentId': 1, 'childId': 346},
                                                        {'parentId': 346, 'childId': 347},
                                                        {'parentId': 1, 'childId': 348},
                                                        {'parentId': 1, 'childId': 349},
                                                        {'parentId': 1, 'childId': 350},
                                                        {'parentId': 1, 'childId': 351},
                                                        {'parentId': 1, 'childId': 352},
                                                        {'parentId': 1, 'childId': 353},
                                                        {'parentId': 1, 'childId': 354},
                                                        {'parentId': 1, 'childId': 355},
                                                        {'parentId': 1, 'childId': 356},
                                                        {'parentId': 1, 'childId': 357},
                                                        {'parentId': 357, 'childId': 358},
                                                        {'parentId': 1, 'childId': 359},
                                                        {'parentId': 359, 'childId': 360},
                                                        {'parentId': 1, 'childId': 361},
                                                        {'parentId': 361, 'childId': 362},
                                                        {'parentId': 1, 'childId': 363}]}

        PATH_TO_MOCK_DATA = 'coeus/articles/apple'
        PATH_TO_TOPIC = 'topic.txt'
        PATH_TO_TEXT = 'text.txt'
        cwd = os.getcwd()
        user_path = cwd.split('coeus')[0]
        topic_path = os.path.join(user_path, PATH_TO_MOCK_DATA, PATH_TO_TOPIC)
        text_path = os.path.join(user_path, PATH_TO_MOCK_DATA, PATH_TO_TEXT)
        topic_file = open(topic_path, 'r')
        text_file = open(text_path, 'r')
        actual_result = Client.generate_mind_map_from_unstructured_text(
            topic_file.read(), text_file.read())
        text_file.close()
        topic_file.close()
        expected_string = str(expected_result_output)
        actual_string = str(actual_result)
        self.assertEqual(
            expected_string,
            actual_string,
            'unstructured :apple final output is not same as expected')


if __name__ == '__main__':
    unittest.main()
